services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    volumes:
      - ./modules/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - default

  orchestrator:
    build: ./modules/orchestrator
    container_name: orchestrator
    depends_on:
      - mqtt-broker

  motors:
    build: ./modules/motors
    container_name: motors
    depends_on:
      - mqtt-broker

  camera:
    build:
      context: ./modules/camera
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "8554:8554"
    restart: unless-stopped
    command: ["-W", "1920", "-H", "1080", "-F", "47", "/dev/video0"]