version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"

  orchestrator:
    build: ./modules/orchestrator
    depends_on:
      - mqtt-broker

  motors:
    build: ./modules/motors
    depends_on:
      - mqtt-broker
