services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: unless-stopped
    volumes:
      - ./modules/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - default

  orchestrator:
    build: ./modules/orchestrator
    container_name: orchestrator
    depends_on:
      - mqtt-broker

  motors:
    build: ./modules/motors
    container_name: motors
    depends_on:
      - mqtt-broker

  ws-server:
    build: modules/ws-server
    container_name: ws-server
    ports:
      - "8765:8765"
    networks:
      - default

  video-stream:
    build: ./modules/video-stream
    container_name: video-stream
    restart: unless-stopped
    privileged: true
    depends_on:
      - ws-server
    networks:
      - default
