services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: unless-stopped
    volumes:
      - ./modules/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - default

  orchestrator:
    build: ./modules/orchestrator
    container_name: orchestrator
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    networks:
      - default

  motors:
    build: ./modules/motors
    container_name: motors
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    networks:
      - default

  video-stream:
    build: ./modules/video-stream
    container_name: video-stream
    restart: unless-stopped
    ports:
      - "8765:8765"
    networks:
      - default

  test-ws:
    build: ./modules/test-ws
    container_name: test-ws
    restart: unless-stopped
    depends_on:
      - video-stream
    networks:
      - default