services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    restart: unless-stopped
    depends_on:
      - web-dashboard
    volumes:
      - ./modules/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - default

  orchestrator:
    build: ./modules/orchestrator
    container_name: orchestrator
    restart: unless-stopped
    depends_on:
      - mqtt
    networks:
      - default

  motors:
    build: ./modules/motors
    container_name: motors
    restart: unless-stopped
    depends_on:
      - mqtt
    networks:
      - default

  ws-server:
    build: ./modules/ws-server
    container_name: ws-server
    restart: unless-stopped
    ports:
      - "8765:8765"
    networks:
      - default

  video-stream:
    build: ./modules/video-stream
    container_name: video-stream
    restart: unless-stopped
    depends_on:
      - ws-server
    volumes:
      - ./testImages:/app/testImages
    networks:
      - default

  test-ws:
    build: ./modules/test-ws
    container_name: test-ws
    restart: unless-stopped
    depends_on:
      - ws-server
    networks:
      - default

  web-dashboard:
    build: ./modules/web-dashboard
    container_name: web-dashboard
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared/module.list:/app/shared/module.list
    restart: unless-stopped
    networks:
      - default
